Olivier/trafwart 1650
geops/trafimage-maps pull request #1176
Opened 2024-06-11 07:07 UTC by oterral

# How to

This PR contains 2 things:
- update from some dependencies but mainly react-spatial and its new canvas save button. So we must test every export button : tarifverbunkarte, Gektunsbereichex2 and the default export button in share menu
- fix to display the dv main layer when dv night and day are not visible on load

# Others

- [x] It's not a hack or at least an unauthorized hack :).
- [x] The images added are optimized.
- [x] Everything in ticket description has been fixed.
- [x] The author of the MR has made its own review before assigning the reviewer.
- [x] The title means something for a human being and follows the [conventional commits](https://www.conventionalcommits.org/) specification.
- [x] The title contains [WIP] if it's necessary.
- [x] Labels applied. if it's a release? a hotfix?
- [x] Tests added.

2024-06-11 07:46 UTC, danji90 requested changes
Looks good, but I found some more things to fix:
- Tarifverbundkarte cypress tests are failing, while testing I noticed some console errors and the highlighting on the map is broken (the zones do not show in red on click). I guess it has to do with the turf upgrade
- https://dev-trafimage-maps-git-olivier-trafwart-1650-geops.vercel.app/ch.sbb.sts?lang=de&layers=ch.sbb.direktverbindungen.night&baselayers=ch.sbb.direktverbindungen.data,ch.sbb.sts.validity.data should switch on night trains only on load, but it always switches on both in the end. This needs to be fixed in the StsMenu, so maybe in a different ticket since it's not directly related.

2024-07-02 08:55 UTC, oterral commented
@danji90  can you re-review please

2024-07-02 09:00 UTC, danji90 approved these changes
@oterral Typo in the comment, otherwise LGTM

2024-07-02 09:06 UTC, oterral commented on src/layers/TarifverbundkarteLayer/TarifverbundkarteLayer.js
> +       * If multiple zones present, the zones are intersected with one another adn the municipality feature
fixed

2024-07-02 09:06 UTC, merged