fix(tracking): add SBB tracking for topics and component events
geops/trafimage-maps pull request #1177
Opened 2024-06-11 15:36 UTC by danji90

# How to

# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] The title means something for a human being and follows the [conventional commits](https://www.conventionalcommits.org/) specification.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] Tests added.

2024-06-13 12:06 UTC, friedjoff requested changes
Sieht insgesamt gut aus, nur ein paar Kleinigkeiten ...

2024-06-13 12:06 UTC, friedjoff commented on src/utils/useTrackTopic.js
> +import { useEffect } from "react";
Diese Funktion würde ich auch in `trackingUtils.js` stecken, hängt ja stark zusammen.

2024-06-13 12:06 UTC, friedjoff commented on src/utils/useTrackTopic.js
> +        pageInstanceID: env === "prod" ? "611081" : "611157",
Damit klar ist, das hier noch was angepasst werden muss:
```suggestion
        pageInstanceID: env === "prod" ? "TODO: prod pageInstanceID" : "TODO: stag pageInstanceID",
```

2024-08-27 09:15 UTC, danji90 commented
@friedjoff Please review again, especially the part about the zoom event tracking

2024-09-17 10:26 UTC, merged