[TRAFKLEIN-534] Use new endpoints for departures
geops/trafimage-maps pull request #881
Opened 2021-03-04 07:59 UTC by edellucien

# How to

Use new endpoints for departures fetching

# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] The title means something for a human being.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] Tests added.

2021-03-10 09:21 UTC, friedjoff approved these changes
Looks fine.

2021-03-11 10:03 UTC, oterral commented on src/popups/DeparturePopup/DeparturePopupContent.js
> +        const offlineDepartures = [...departures].map((d) => {
no one letter variable

2021-03-11 10:04 UTC, oterral commented on src/popups/DeparturePopup/DeparturePopupContent.js
> +          return d;
```suggestion
          return {...d, estimatedTimeLocal:null, timetabledTimeLocal: null};
```

2021-03-11 10:04 UTC, oterral commented on src/popups/DeparturePopup/DeparturePopupContent.js
> +          return d;
it will avoid eslint comments

2021-03-11 10:05 UTC, oterral commented on src/popups/DeparturePopup/DeparturePopupContent.js
> +                    }}
duplicate styling

2021-03-11 10:07 UTC, oterral requested changes
minor comments otherwise lgtm

2021-03-15 15:48 UTC, merged