Disable pagination for zweitausbildung poi popup.
geops/trafimage-maps pull request #899
Opened 2021-04-29 10:04 UTC by mhaertwig

Introduce `hidePagination` popup property, display all popup items for zweitausbildung pois without pagination.

2021-04-29 10:06 UTC, mhaertwig commented on package.json
> +  "version": "1.5.13",
Didn't count for a long time.

2021-04-29 11:51 UTC, oterral requested changes
With this PR you fix the issue but you potentially creates others. For example if there is another layer that is queryable , the pagination will not be displayed. 

The Popup should not hide the pagination but  should decide if  features of the corresponding layers are displayed in one page or one pro page. and if it's the case the `features` array should not be a flat map of features but an array containing feature or array of features.

```
const features = [
feature1Layer1,
feature2Layer1,
[ feature1Layer2, feature2Layer2 ]
]; 
```

like this you keep the pagination and you avoid adding a new  property to the popup.  Or even better you place the `feature` property by  the  `features` property.

2021-05-18 13:33 UTC, oterral approved these changes

2021-05-18 13:33 UTC, oterral commented
I merge this since the topic is already on production

2021-05-18 13:34 UTC, merged