MUI Select everywhere
geops/trafimage-maps pull request #963
Opened 2022-01-05 14:52 UTC by danji90

# How to

# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] The title means something for a human being.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] Tests added.

2022-01-10 09:44 UTC, danji90 commented
@oterral _disableEnforceFocus: true_ seems to have done the trick

2022-01-11 11:12 UTC, oterral requested changes
It seems there is duplicated styles in langSelect and projectionSelect, can we put them in the generic Select component ?

2022-01-11 11:16 UTC, oterral requested changes
- margin between icon and text are not the same for login text and language box
- language box is not aligned with login text

2022-01-11 15:57 UTC, danji90 commented
@oterral LGTM?

2022-01-12 07:30 UTC, oterral commented on src/components/Select/Select.js
> +      '& Mui-focused .MuiOutlinedInput-notchedOutline': {
& .Mui-focused

2022-01-12 07:31 UTC, oterral commented on src/components/Select/Select.js
> +      '& Mui-focused .MuiOutlinedInput-notchedOutline': {
```suggestion
      '& .Mui-focused .MuiOutlinedInput-notchedOutline': {
```

2022-01-12 07:34 UTC, oterral commented
@danji90  there is BAFU layers change in this PR is it normal ?

2022-01-12 07:40 UTC, oterral approved these changes
Very nice thanks, Ihave fixed the border of the select box on mobile

2022-01-12 08:12 UTC, merged